---
- name: Configure web servers
  hosts: webservers
  become: true

  vars_files:
    - group_vars/all.yml

  tasks:
    - name: Create devops user
      tags: user
      user:
        name: devops
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    - name: Install required packages
      tags: packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes

    - name: Start and enable nginx service
      tags: nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy custom index.html to web root
      tags: html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

