- name: Configure web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Create devops user
      user:
        name: devops
        groups: sudo
        append: yes
        state: present
        shell: /bin/bash

  roles:
    - nginx

